/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import React, { useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { Select } from "@react-three/postprocessing";
import * as THREE from "three";

export function Room(props) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + "models/optimized-room.glb");
  const matcapTexture = useTexture(import.meta.env.BASE_URL + "images/textures/mat1.png");

  // Materials were being recreated with `new THREE.MeshPhongMaterial(...)`
  // on every render (each re-render allocated 7 fresh Three.js material
  // objects, forcing GPU re-uploads). Memoized so they're created once and
  // reused across re-renders — same instances persist for the mesh's lifetime.
  const curtainMaterial = useMemo(
    () => new THREE.MeshPhongMaterial({ color: "#d90429" }),
    []
  );

  const bodyMaterial = useMemo(
    () => new THREE.MeshPhongMaterial({ map: matcapTexture }),
    [matcapTexture]
  );

  const tableMaterial = useMemo(
    () => new THREE.MeshPhongMaterial({ color: "#582f0e" }),
    []
  );

  const radiatorMaterial = useMemo(
    () => new THREE.MeshPhongMaterial({ color: "#fff" }),
    []
  );

  const compMaterial = useMemo(
    () => new THREE.MeshStandardMaterial({ color: "#fff" }),
    []
  );

  const pillowMaterial = useMemo(
    () => new THREE.MeshPhongMaterial({ color: "#8338ec" }),
    []
  );

  const chairMaterial = useMemo(
    () => new THREE.MeshPhongMaterial({ color: "#000" }),
    []
  );

  return (
    <group {...props} dispose={null}>
      {/*
        EffectComposer/SelectiveBloom lived here before, using a raw mesh
        ref as the `selection` prop. That raced against this component's
        async GLTF/texture loading (via Suspense) and crashed with
        "Cannot read properties of undefined (reading 'layers')" once the
        bloom effect tried to read the ref before it was populated.

        Bloom is now owned by HeroExperience.jsx, wrapped in <Selection>,
        which provides React context instead of relying on ref timing.
        This mesh just needs to opt in via <Select enabled> below — no ref,
        no race, and no duplicate EffectComposer running a second render
        pass on top of the one in HeroExperience.
      */}
      <mesh
        geometry={nodes._________6_blinn1_0.geometry}
        material={curtainMaterial}
      />
      <mesh geometry={nodes.body1_blinn1_0.geometry} material={bodyMaterial} />
      <mesh geometry={nodes.cabin_blinn1_0.geometry} material={tableMaterial} />
      <mesh
        geometry={nodes.chair_body_blinn1_0.geometry}
        material={chairMaterial}
      />
      <mesh geometry={nodes.comp_blinn1_0.geometry} material={compMaterial} />
      <Select enabled>
        <mesh
          geometry={nodes.emis_lambert1_0.geometry}
          material={materials.lambert1}
        />
      </Select>
      <mesh
        geometry={nodes.handls_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.kovrik_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_bl_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_white_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.miuse_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pCylinder5_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pillows_blinn1_0.geometry}
        material={pillowMaterial}
      />
      <mesh
        geometry={nodes.polySurface53_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0.geometry}
        material={radiatorMaterial}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0001.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.railing_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_bttns_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_vac_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.stylus_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh geometry={nodes.table_blinn1_0.geometry} material={tableMaterial} />
      <mesh
        geometry={nodes.tablet_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.triangle_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vac_black_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuum1_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuumgrey_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vires_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
      />
    </group>
  );
}

useGLTF.preload(import.meta.env.BASE_URL + "models/optimized-room.glb");
