import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

/**
 * Night scene: Gargantua-style black hole as centerpiece, with a couple of
 * planets drifting around it. Uses the .glb files already in /public/models —
 * loaded generically via <primitive>, no hand-authored node names needed
 * (unlike Room.jsx / Computer.jsx which were auto-generated by gltfjsx).
 *
 * Expects these files in /public/models/:
 *   gargantua_the_black_hole.glb
 *   stylized_planet.glb
 *   purple_planet.glb
 *   sun.glb
 */

const SpaceScene = () => {
  const blackHole = useGLTF(import.meta.env.BASE_URL + 'models/gargantua_the_black_hole.glb')
  const planetA = useGLTF(import.meta.env.BASE_URL + 'models/stylized_planet.glb')
  const planetB = useGLTF(import.meta.env.BASE_URL + 'models/purple_planet.glb')
  const planetC = useGLTF(import.meta.env.BASE_URL + 'models/sun.glb')

  const blackHoleRef = useRef()
  const planetARef = useRef()
  const planetBRef = useRef()
  const planetCRef = useRef()

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    if (blackHoleRef.current) {
      blackHoleRef.current.rotation.z = t * 0.1
    }
    if (planetARef.current) {
      planetARef.current.position.x = Math.cos(t * 0.15) * 4.5
      planetARef.current.position.z = Math.sin(t * 0.15) * 4.5 - 2
      planetARef.current.rotation.y = t * 0.3
    }
    if (planetBRef.current) {
      planetBRef.current.position.x = Math.cos(t * 0.1 + Math.PI) * 6
      planetBRef.current.position.z = Math.sin(t * 0.1 + Math.PI) * 6 - 2
      planetBRef.current.rotation.y = t * 0.2
    }
    if (planetCRef.current) {    
      planetCRef.current.position.x = Math.cos(t * 0.07) * 8
      planetCRef.current.position.z = Math.sin(t * 0.07) * 8 - 2
      planetCRef.current.rotation.y = t * 0.15
    }

    
  })

  return (
    <group position={[0, 0, -3]}>
      <group ref={blackHoleRef} scale={1.4}>
        <primitive object={blackHole.scene} />
      </group>

      <group ref={planetARef} scale={0.25}>
        <primitive object={planetA.scene} />
      </group>

      <group ref={planetBRef} scale={0.35}>
        <primitive object={planetB.scene} />
      </group>

      <group ref={planetCRef} scale={0.5}>
        <primitive object={planetC.scene} />
      </group>

      <ambientLight intensity={0.35} color="#5fb8b0" />
      <pointLight position={[0, 0, 0]} intensity={3} color="#FABF65" distance={20} />
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/gargantua_the_black_hole.glb')
useGLTF.preload(import.meta.env.BASE_URL + 'models/stylized_planet.glb')
useGLTF.preload(import.meta.env.BASE_URL + 'models/purple_planet.glb')
useGLTF.preload(import.meta.env.BASE_URL + 'models/sun.glb')

export default SpaceScene
